// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xZcvLtVpW7RJBFs_VsrzixJKrho-jAU',
    appId: '1:599811524565:web:2860868568f1de39389f5c',
    messagingSenderId: '599811524565',
    projectId: 'diploma-1f433',
    authDomain: 'diploma-1f433.firebaseapp.com',
    storageBucket: 'diploma-1f433.firebasestorage.app',
    measurementId: 'G-JFRMCGD8RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZuX_B-V7jaG-fd3CryyRGAv1bDAYihUM',
    appId: '1:599811524565:android:39463d2074838f15389f5c',
    messagingSenderId: '599811524565',
    projectId: 'diploma-1f433',
    storageBucket: 'diploma-1f433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJr3_xe--B3Hr6li06wlcOO-l41joBPRs',
    appId: '1:599811524565:ios:66910e2c08490b67389f5c',
    messagingSenderId: '599811524565',
    projectId: 'diploma-1f433',
    storageBucket: 'diploma-1f433.firebasestorage.app',
    iosClientId: '599811524565-s8p3idj8b9jgpau1dpvf8m5vt9t9gpub.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJr3_xe--B3Hr6li06wlcOO-l41joBPRs',
    appId: '1:599811524565:ios:66910e2c08490b67389f5c',
    messagingSenderId: '599811524565',
    projectId: 'diploma-1f433',
    storageBucket: 'diploma-1f433.firebasestorage.app',
    iosClientId: '599811524565-s8p3idj8b9jgpau1dpvf8m5vt9t9gpub.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3xZcvLtVpW7RJBFs_VsrzixJKrho-jAU',
    appId: '1:599811524565:web:de0f272649cf941c389f5c',
    messagingSenderId: '599811524565',
    projectId: 'diploma-1f433',
    authDomain: 'diploma-1f433.firebaseapp.com',
    storageBucket: 'diploma-1f433.firebasestorage.app',
    measurementId: 'G-WY92HYH2RP',
  );
}
